name: "train"
n_gpu: 1

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  weight_decay: 0.0001

batch_size: 32
num_samples: 64000

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 1

sinc_out_channels: 128
res1_out_channels: 20
res2_out_channels: 128

arch:
  _target_: hw_as.model.RawNet2
  sinc_config:
    out_channels: ${res1_out_channels}
    kernel_size: 1024
    stride: 1
    min_low_hz: 0
    min_band_hz: 0
  res1_config:
    in_channels: ${res1_out_channels}
    out_channels: ${res1_out_channels}
    num_layers: 2
    sep_first: true
  res2_config:
    in_channels: ${res1_out_channels}
    out_channels: ${res2_out_channels}
    num_layers: 4
    sep_first: false
  gru_config:
    input_size: ${res2_out_channels}
    hidden_size: 1024
    num_layers: 3
    batch_first: true

metrics:
  - _target_: hw_as.metric.EER
    name: EER
    epoch_level: true

loss:
  _target_: hw_as.loss.CrossEntropyLossWrapper
  weight: [1, 9]

data:
  train:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: hw_as.datasets.ASVspoofDataset
        protocol_path: data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt
        audio_dir: data/LA/ASVspoof2019_LA_train/flac
        num_samples: ${num_samples}
  val:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: hw_as.datasets.ASVspoofDataset
        protocol_path: data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.dev.trl.txt
        audio_dir: data/LA/ASVspoof2019_LA_dev/flac
        num_samples: ${num_samples}
  test:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: hw_as.datasets.ASVspoofDataset
        protocol_path: data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
        audio_dir: data/LA/ASVspoof2019_LA_eval/flac
        num_samples: ${num_samples}
trainer: 
  epochs: 50
  save_dir: "saved/"
  save_period: 5
  verbosity: 2
  monitor: "min val_loss"
  early_stop: 100
  visualize: "wandb"
  wandb_project: "as_project"
  wandb_run_name: "one_batch_test"
  len_epoch: 100
  grad_norm_clip: 50

wandb_key: 91898ab676432e8d5689a2ce4a88f7131dc1e45c